# Generated by Django 4.1.10 on 2023-12-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
